# default configuration
baseURL = ""
languageCode = "en-uk"
summaryLength = "3"
theme = "kross-hugo"
title = "SCS-USJ"

# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"


# js plugin
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"


# menu
[[menu.main]]
URL = "about"
name = "About"
weight = 1

[[menu.main]]
URL = "blog"
name = "Blog"
weight = 2

[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 3

[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4


# default parameters
[params]
home = "Home"
logo = ""
# theme color
theme_color = "#08306b"
# contact info
phone = "ttalagala@sjp.ac.lk"
email = "Dr Thiyanga S. Talagala (Former Coordinator: 2020-2023)"
address = "Department of Statistics, Faculty of Applied Sciences, University of Sri Jayewardenepura, Nugegoda, 10250, Sri Lanka"
# meta description
author = ""
description = "This is meta description"
# google analytics
google_analytics_id = "" # Your ID
# copyright
copyright = "Copyright &copy; 2020 Thiyanga S. Talagala &sum; HUGO" 


# preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use png, jpg, svg or gif format

# contact
[params.contact]
enable = false
form_action = "#" # contact form works with : https://formspree.io

# google map
[params.map]
enable = false
gmap_api = "https://www.google.lk/maps/place/Faculty+of+Applied+Sciences/@6.8539836,79.9034718,17z/data=!4m12!1m6!3m5!1s0x3ae25a8936886579:0xa8c769f4b86d85b5!2sUniversity+of+Sri+Jayewardenepura!8m2!3d6.8539836!4d79.9056658!3m4!1s0x3ae25a89acf0dc8b:0xbcdcf18ae90044ff!8m2!3d6.8549064!4d79.9034277"
map_latitude = "6.931970"
map_longitude = "79.857750"
map_marker = "images/marker.png"

# social site
[[params.social]]
icon = ""
URL = "#"

[[params.social]]
icon = ""
URL = "#"

[[params.social]]
icon = ""
URL = "#"

[[params.social]]
icon = ""
URL = "#"
