---
title: "DSjobtracker - Data visualisation"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(DSjobtracker)
library(ggplot2)
library(plotly)
library(tidyverse)
library(magrittr)
library(packrat)
library(here)
library(viridis)
```

# Software

Column {data-width=500}
-----------------------------------------------------------------------

### Statistical Software

```{r, comment=NA, warning=FALSE, include=FALSE}
data(DStidy)
head(DStidy)
```

```{r, comment=NA, warning=FALSE, include=FALSE}
DStidy$Statistical_software <- paste(DStidy$R,DStidy$SAS,DStidy$SPSS,DStidy$Python,DStidy$MAtlab,sep = "::")

unique(DStidy$Statistical_software)

d1 <- DStidy$Statistical_software %>% table() %>% as.data.frame()
names(d1) <- c('Statistical_software', 'Frequency')
d1 <- d1[order(d1$Frequency, decreasing = T),]

d1
```

```{r, comment=NA, warning=FALSE, include=FALSE}
DStidy$Statistical_software[DStidy$Statistical_software=="1::0::0::1::0"] <-"R & Python"
DStidy$Statistical_software[DStidy$Statistical_software=="0::0::0::0::0"] <-"No Statistical softwares"
DStidy$Statistical_software[DStidy$Statistical_software=="0::0::0::1::0"] <-"Python only"
DStidy$Statistical_software[DStidy$Statistical_software=="1::1::0::1::0"] <-"R, SAS & Python only "

DStidy$Statistical_software[DStidy$Statistical_software=="0::1::0::0::0"] <-"SAS only"

DStidy$Statistical_software[DStidy$Statistical_software=="1::0::0::0::0"] <-"R only"

DStidy$Statistical_software[DStidy$Statistical_software=="1::0::0::1::1" | DStidy$Statistical_software=="0::1::1::0::0"| DStidy$Statistical_software=="1::1::1::1::0"| DStidy$Statistical_software=="1::1::1::1::1"| DStidy$Statistical_software=="1::1::0::0::0"| DStidy$Statistical_software=="1::0::1::0::0"| DStidy$Statistical_software=="0::1::0::1::0"| DStidy$Statistical_software=="1::1::1::0::1"| DStidy$Statistical_software=="1::0::1::1::1"| DStidy$Statistical_software=="1::0::1::1::0"| DStidy$Statistical_software=="1::1::1::0::0"| DStidy$Statistical_software=="1::1::0::1::1"| DStidy$Statistical_software=="1::1::0::0::1"| DStidy$Statistical_software=="0::1::0::1::1"| DStidy$Statistical_software=="0::0::1::0::0"| DStidy$Statistical_software=="1::0::0::0::1"| DStidy$Statistical_software=="0::0::0::1::1"] <-"Other Statistical software"

unique(DStidy$Statistical_software)

d1 <- DStidy$Statistical_software %>% table() %>% as.data.frame()
names(d1) <- c('Statistical_software', 'Frequency')
d1 <- d1[order(d1$Frequency, decreasing = T),]

d1

```

```{r}
d1 <- DStidy$Statistical_software %>% table() %>% as.data.frame()
names(d1) <- c('Statistical_software', 'Frequency')
d1 <- d1[order(d1$Frequency, decreasing = T),]


plot1 <- ggplot(d1, aes(x= reorder(Statistical_software, Frequency), y=Frequency))+ labs(y="Number of advertisements", x="") + geom_bar(stat = "identity", width = 0.5, fill ="#FC4E07") +coord_flip()

ggplotly(plot1)
```

Column {data-width=500}
-----------------------------------------------------------------------

### Programming software

```{r, comment=NA, warning=FALSE, include=FALSE}
DStidy$Programming_software <- paste(DStidy$Spark,DStidy$Scala,DStidy$Java,DStidy$C,DStidy$C.,DStidy$C..,DStidy$pyspark,sep = "::")



d2 <- DStidy$Programming_software%>% table() %>% as.data.frame()
names(d2) <- c('Programming_software', 'Frequency')
d2 <- d2[order(d2$Frequency, decreasing = T),]

d2
```

```{r, comment=NA, warning=FALSE, include=FALSE}
DStidy$Programming_software[DStidy$Programming_software=="0::0::0::0::0::0::0"] <-"No programming software"
DStidy$Programming_software[DStidy$Programming_software=="1::0::0::0::0::0::0"] <-"Spark only"
DStidy$Programming_software[DStidy$Programming_software=="0::0::1::0::0::0::0"] <-"Java only"
DStidy$Programming_software[DStidy$Programming_software=="0::1::0::0::0::0::0"] <- "Scala only" 
DStidy$Programming_software[DStidy$Programming_software=="0::0::0::0::0::1::0"| DStidy$Programming_software=="1::1::0::0::0::0::0" | DStidy$Programming_software=="0::0::0::0::0::0::1"| DStidy$Programming_software=="0::0::0::1::0::0::0"| DStidy$Programming_software=="0::1::1::0::0::1::0"| DStidy$Programming_software=="1::0::1::0::0::0::0"| DStidy$Programming_software=="1::1::1::0::0::0::0"| DStidy$Programming_software=="0::0::1::0::0::1::0"| DStidy$Programming_software=="0::1::1::0::0::0::0"| DStidy$Programming_software=="0::0::1::1::0::0::0"| DStidy$Programming_software=="1::0::1::1::0::1::0"| DStidy$Programming_software=="0::0::0::1::0::0::1"|DStidy$Programming_software=="0::0::1::0::1::0::0"|DStidy$Programming_software=="0::0::1::1::0::1::0"|DStidy$Programming_software=="0::1::0::0::0::1::0"|DStidy$Programming_software=="1::0::1::0::0::0::1"|DStidy$Programming_software=="1::0::1::0::0::1::0"|DStidy$Programming_software=="1::1::0::0::0::0::1"|DStidy$Programming_software=="1::1::1::0::0::1::0"|DStidy$Programming_software=="1::1::1::0::1::0::0"] <-"Other programmimg software"

d2 <- DStidy$Programming_software%>% table() %>% as.data.frame()
names(d2) <- c('Programming_software', 'Frequency')
d2 <- d2[order(d2$Frequency, decreasing = T),]

d2

```

```{r}
plot2 <- ggplot(d2, aes(x= reorder(Programming_software, Frequency), y=Frequency))+ labs(y="Number of advertisements", x="") + geom_bar(stat = "identity", width = 0.5, fill ="#009E73") +coord_flip()

ggplotly(plot2)
```


### Database software and Query languages

```{r, comment=NA, warning=FALSE, include=FALSE}
DStidy$database_softwares_and_query_languages <- paste(DStidy$OLE_DB,DStidy$SQL,DStidy$NoSQL,DStidy$MySQL,DStidy$RDBMS,DStidy$MongoDB,DStidy$Hadoop,sep = "::")

unique(DStidy$database_softwares_and_query_languages)

d3 <- DStidy$database_softwares_and_query_languages%>% table() %>% as.data.frame()
names(d3) <- c('database_softwares_and_query_languages', 'Frequency')
d3 <- d3[order(d3$Frequency, decreasing = T),]

d3
```

```{r, comment= NA, warning=FALSE, include=FALSE}
DStidy$database_softwares_and_query_languages[DStidy$database_softwares_and_query_languages=="0::0::0::0::0::0::0"] <-"No database software and/or query language"
DStidy$database_softwares_and_query_languages[DStidy$database_softwares_and_query_languages=="0::1::0::0::0::0::0"] <-"SQL only"
DStidy$database_softwares_and_query_languages[DStidy$database_softwares_and_query_languages=="0::1::0::1::0::0::0"] <-"SQL & MySQL only"
DStidy$database_softwares_and_query_languages[DStidy$database_softwares_and_query_languages=="0::1::0::0::0::0::1"] <-"SQL & Handoop only"
DStidy$database_softwares_and_query_languages[DStidy$database_softwares_and_query_languages=="0::1::1::0::0::0::0"] <-"SQL & NoSQL only"

DStidy$database_softwares_and_query_languages[DStidy$database_softwares_and_query_languages=="0::0::0::1::0::0::0" | DStidy$database_softwares_and_query_languages=="0::0::0::0::0::0::1"| DStidy$database_softwares_and_query_languages=="0::1::0::1::0::0::1" | DStidy$database_softwares_and_query_languages=="0::0::0::0::1::0::0"| DStidy$database_softwares_and_query_languages=="0::1::0::0::0::1::0"| DStidy$database_softwares_and_query_languages=="0::1::0::0::0::1::1"| DStidy$database_softwares_and_query_languages=="0::1::0::0::1::0::1"| DStidy$database_softwares_and_query_languages=="1::1::0::0::0::0::0"| DStidy$database_softwares_and_query_languages=="0::0::1::0::0::0::0"| DStidy$database_softwares_and_query_languages=="0::0::1::0::1::0::1"| DStidy$database_softwares_and_query_languages=="0::1::0::0::1::0::0"| DStidy$database_softwares_and_query_languages=="0::1::1::0::0::0::1"| DStidy$database_softwares_and_query_languages=="0::1::1::0::1::0::0"|DStidy$database_softwares_and_query_languages=="0::1::1::0::1::0::1"|DStidy$database_softwares_and_query_languages=="0::1::1::1::0::0::0"| DStidy$database_softwares_and_query_languages=="0::1::0::1::1::0::1"| DStidy$database_softwares_and_query_languages=="0::1::0::1::1::0::0"| DStidy$database_softwares_and_query_languages=="0::0::0::0::0::1::1"] <-"Other"

unique(DStidy$database_softwares_and_query_languages)

d3 <- DStidy$database_softwares_and_query_languages %>% table() %>% as.data.frame()
names(d3) <- c('database_softwares_and_query_languages', 'Frequency')
d3 <- d3[order(d3$Frequency, decreasing = T),]

d3
```


```{r}
plot3 <- ggplot(d3, aes(x= reorder(database_softwares_and_query_languages, Frequency), y=Frequency))+ labs(y="Number of advertisements", x="") + geom_bar(stat = "identity", width = 0.5, fill ="#56B4E9") +coord_flip()

ggplotly(plot3)
```
