---
title: "DSjobtracker - Data visualisation"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```





Column {data-width=800}
-----------------------------------------------------------------------
#### Countrywise composition of number of Statistical Job Advertistments 
```{r}
devtools::install_github("thiyangt/DSjobtracker")
library(DSjobtracker)
library(maps)
library(viridis)
library(mapproj)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(tidyr)
library(ggrepel)
library(plotly)
library(R.utils)

#Importing the data sets

data("DStidy")
data<-map_data("world")
worlddata<-data.frame(world.cities)

#Taking to same consistency

worlddata[worlddata=="USA"]<-"United States"
worlddata[worlddata=="UK"]<-"United Kingdom"


#Making a frequency table of vacanvies for the countries


summaries<-as.data.frame(table(DStidy$Job_Country))
colnames(summaries)<-c("country.etc","Frequency")


#Making to lower case

summaries$country.etc<-str_to_lower(summaries$country.etc)
worlddata$country.etc<-str_to_lower(worlddata$country.etc)


#Filtering the needed countries

datall<-worlddata %>% filter(country.etc%in%summaries$country.etc)

#Joining the needed countries and Frequencies

dup_data_joined<-left_join(datall,summaries)

#Extracting a special row for a country in Canada
special_row<-dup_data_joined[dup_data_joined$name=="Edmonton",]
data_joined<-dup_data_joined[!duplicated(dup_data_joined[,c("country.etc")]),]

#Removing the row for Canada and pasting the special row
data_joined<-data_joined[-c(10),]
data_joined<-rbind(data_joined,special_row)

#Making the Countries to upper case letters
data_joined$country.etc<-capitalize(data_joined$country.etc,collapse=" ")
data_joined[data_joined=="Sri lanka"]<-"Sri Lanka"
data_joined[data_joined=="United states"]<-"United States"
data_joined[data_joined=="United kingdom"]<-"United Kingdom"
data_joined[data_joined=="new zealand"]<-"New Zealand"
data_joined[data_joined=="United arab emirates"]<-"United Arab Emirates"
data_joined[data_joined=="New caledonia"]<-"New Caledonia"

#Entering a new column with a text

data_joined<-data_joined%>%
  arrange(Frequency)%>%
  mutate(name=factor(country.etc,unique(country.etc)))%>%
  mutate(mytext=paste("Country: ",name,"\n","Number of Job Advertistments: ",Frequency,sep = ""))



#Plotting the map
plot<-data_joined%>%
  ggplot() +
  geom_polygon(data = data, aes(x=long, y = lat, group = group), fill="grey", alpha=0.9) +
  geom_point( data=data_joined, aes(x=long, y=lat,color=Frequency, text=mytext),size=4) +
   
  scale_color_viridis() +geom_text_repel(data=data_joined %>% arrange(Frequency),aes(x=long,y=lat,label=country.etc),size=3)+
  theme_void() + coord_map()
ggplotly(plot,tooltip = "text")
```


Column {data-width=350}{.tabset .tabset-fade}
-----------------------------------------------------------------------
### C1

```{r}
p <- ggplot(data_joined, aes(x = reorder(country.etc,Frequency), y = Frequency,text=paste("Number of Job Advertistments: ",Frequency)))+
  geom_col( width = 0.7,fill="steelblue")+coord_flip()+ylab("Number of Job Advertistements")+xlab("Country")
ggplotly(p,tooltip="text")


```


